apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dolphindbWebserver.fullName" . }}
  labels:
    dolphindb.io/component: dolphindb-webserver
    app.kubernetes.io/name: {{ include "dolphindbWebserver.fullName" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      dolphindb.io/component: dolphindb-webserver
      app.kubernetes.io/name: {{ include "dolphindbWebserver.fullName" . }}
  template:
    metadata:
      name: {{ include "dolphindbWebserver.fullName" . }}
      labels:
        dolphindb.io/component: dolphindb-webserver
        app.kubernetes.io/name: {{ include "dolphindbWebserver.fullName" . }}
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: {{ .Values.global.serviceAccount }}
      containers:
        - name: dolphindb-webserver
          image: {{ include "repository" . }}/dolphindb-webserver:{{ include "dolphindbWebserver.imageTag" . }}
          imagePullPolicy: IfNotPresent
          env:
            {{- include "mgr.env" . | indent 10}}
          - name: NodePortIP
            value: {{ .Values.nodePortIP }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
